### ISSUE TITLE
missing authority of `evodextester`

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/evodex#189]
**Describe the bug**
missing authority of `evodextester` account , even though i am logged in using the account demodemodemo

using the jungle testnet version of the app
 
**To Reproduce**
1. Go to vote fee
2. Enter percentage and click vote

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5632966/92853664-5211a000-f3ad-11ea-8641-23274a32ded9.png)

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser Chrome

**Comment by PixelNoob** [comment]
This happens because when you create a token pair you can set yourself as the fee master, this is the case for evodextester and the EOSJUNG pair , so nobody else can vote on the fee except him.

I can add this parameter to the API so that we know who has control of setting the fee and correct the UI accordingly.

**Comment by PixelNoob** [comment]
NOTE: This is not an issue on mainnet since we hard-coded the pairs we list and all of them have wevotethefee as a fee master, so we can set a medium priority to it.
